version : '3.7'

services:
    app:
        network_mode: "host"
        env_file:
        - .env
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_URL: "${OVERCOOKED_URL:-https://github.com/AlexWanghaoming/overcooked_ai}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-master}"
                HARL_URL: "${HARL_URL:-https://github.com/AlexWanghaoming/human_aware_rl.git}"
                HARL_BRANCH: "${HARL_BRANCH:-master}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "central.github.com:140.82.112.3"
            - "assets-cdn.github.com:140.82.112.3"
            - "github.map.fastly.net:151.101.1.6"
            - "github.global.ssl.fastly.net:151.101.1.6"
            - "gist.github.com:140.82.112.3"
            - "github.io:185.199.108.153"
            - "github.com:140.82.112.3"
            - "api.github.com:140.82.112.3"
            - "codeload.github.com:140.82.112.3"
            - "github-cloud.s3.amazonaws.com:72.21.206.80"
            - "github-com.s3.amazonaws.com:72.21.206.80"
            - "github-production-release-asset-2e65be.s3.amazonaws.com:72.21.206.80"
            - "github-production-user-asset-6210df.s3.amazonaws.com:72.21.206.80"
            - "github-production-repository-file-5c1aeb.s3.amazonaws.com:72.21.206.80"
            - "githubstatus.com:185.199.108.153"
            - "github.community:140.82.113.18"
            - "raw.github.com:140.82.112.3"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "80:5000"
        volumes:
            - "${AGENTS_DIR:-./server/static/assets/agents}:/app/static/assets/agents"
            - "${TRAJECTORIES_DIR:-./server/static/assets/trajectories}:/app/static/assets/trajectories"
